name: pyecog
dependencies:
  - jupyter
  - python=3.6
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - h5py
  - xlrd
  - bokeh
  - scikit-learn
  - pip:
    - pomegranate
    - pyqtgraph
